### ISSUE TITLE
Upgrade for 3.x

### ISSUE THREAD

**Issue by vaughany** [CakeDC/favorites#16]
Hi all. I know a plugin such as this is not a high priority development, but is there any chance you're going to release a version for 3.x?  I want what this plugin does in my project, but don't want to reinvent the wheel (and don't stand much of a chance of being able to do it myself).

If not, no worries, but I thought I'd open an issue nonetheless.

**Comment by pmoraes** [comment]
Hi @vaughany, this issue will be being discuted internally and I will let you know as soon as possible.

Thanks.

**Comment by pmoraes** [comment]
HI @vaughany this upgrade is on hold by us yet, but if you want to do this you can go ahead. You can fork our repo and to do a PR with the upgrade for us.

By any doubts, pĺease let us know.

**Comment by Megslalk** [comment]
Closing issue - Please re-open if necessary!
